CREATE TYPE "public"."culture_type" AS ENUM('cereals', 'vegetables', 'vineyard', 'fruit_trees', 'pasture', 'fodder', 'industrial_crops', 'other_crops');--> statement-breakpoint
CREATE TYPE "public"."site_status" AS ENUM('active', 'completed');--> statement-breakpoint
ALTER TYPE "public"."machine_type" ADD VALUE 'tractor' BEFORE 'other';--> statement-breakpoint
ALTER TYPE "public"."machine_type" ADD VALUE 'combine_harvester' BEFORE 'other';--> statement-breakpoint
ALTER TYPE "public"."machine_type" ADD VALUE 'forage_harvester' BEFORE 'other';--> statement-breakpoint
ALTER TYPE "public"."machine_type" ADD VALUE 'sprayer' BEFORE 'other';--> statement-breakpoint
ALTER TYPE "public"."machine_type" ADD VALUE 'seeder' BEFORE 'other';--> statement-breakpoint
ALTER TYPE "public"."machine_type" ADD VALUE 'baler' BEFORE 'other';--> statement-breakpoint
ALTER TYPE "public"."machine_type" ADD VALUE 'tedder' BEFORE 'other';--> statement-breakpoint
ALTER TYPE "public"."machine_type" ADD VALUE 'mower' BEFORE 'other';--> statement-breakpoint
ALTER TYPE "public"."machine_type" ADD VALUE 'trailer' BEFORE 'other';--> statement-breakpoint
ALTER TYPE "public"."machine_type" ADD VALUE 'slurry_tanker' BEFORE 'other';--> statement-breakpoint
ALTER TYPE "public"."machine_type" ADD VALUE 'forestry_tractor' BEFORE 'other';--> statement-breakpoint
ALTER TYPE "public"."machine_type" ADD VALUE 'vineyard_tractor' BEFORE 'other';--> statement-breakpoint
CREATE TABLE "agricultural_surfaces" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"user_id" varchar NOT NULL,
	"total_hectares" real NOT NULL,
	"culture_type" "culture_type",
	"usage_description" text,
	"irrigation" boolean DEFAULT false,
	"declaration_year" integer NOT NULL,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "construction_sites" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"user_id" varchar NOT NULL,
	"name" text NOT NULL,
	"location" text,
	"start_date" timestamp NOT NULL,
	"end_date" timestamp,
	"status" "site_status" DEFAULT 'active' NOT NULL,
	"fiscal_year" integer NOT NULL,
	"notes" text,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "machine_site_assignments" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"machine_id" varchar NOT NULL,
	"site_id" varchar NOT NULL,
	"start_date" timestamp NOT NULL,
	"end_date" timestamp,
	"comment" text,
	"created_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "promo_code_redemptions" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "promo_code_redemptions_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"promo_code_id" integer NOT NULL,
	"user_id" varchar NOT NULL,
	"redeemed_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "promo_codes" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "promo_codes_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"code" varchar(50) NOT NULL,
	"duration_months" integer DEFAULT 12 NOT NULL,
	"max_uses" integer,
	"current_uses" integer DEFAULT 0 NOT NULL,
	"valid_from" timestamp DEFAULT now(),
	"valid_until" timestamp,
	"is_active" boolean DEFAULT true NOT NULL,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now(),
	CONSTRAINT "promo_codes_code_unique" UNIQUE("code")
);
--> statement-breakpoint
ALTER TABLE "fuel_entries" ADD COLUMN "site_id" varchar;--> statement-breakpoint
ALTER TABLE "promo_code_redemptions" ADD CONSTRAINT "promo_code_redemptions_promo_code_id_promo_codes_id_fk" FOREIGN KEY ("promo_code_id") REFERENCES "public"."promo_codes"("id") ON DELETE cascade ON UPDATE no action;